### ISSUE TITLE
Won't compile with Pony 0.15

### ISSUE THREAD

**Issue by tj800x** [jemc/pony-crdt#1]
Building ../crdt -> .../Projects/pony/pony-crdt/crdt
Error:
.../Projects/pony/pony-crdt/crdt/g_counter.pony:54:20: syntax error: unterminated type parameters
  fun ref increment[D: GCounter[A] #write = GCounter[A] trn](
                   ^
    Info:
    .../Projects/pony/pony-crdt/crdt/g_counter.pony:54:36: expected terminating ] before here
      fun ref increment[D: GCounter[A] #write = GCounter[A] trn](
                                       ^

[pony-crdt]$ ponyc --version
0.15.0-d603ecce [release]
compiled with: llvm 3.9.1 -- Apple LLVM version 8.1.0 (clang-802.0.42)

**Comment by jemc** [comment]
Thanks for your interest in this repo!

The feature I've been using (`#write`) has not actually made it into Pony yet, and I've been working against an experimental branch of ponyc.  See this RFC for details: https://github.com/ponylang/rfcs/pull/93

**Comment by tj800x** [comment]
Good to know.  Thank you.

**Comment by jemc** [comment]
For whatever it's worth, I decided to not rely on `#write` for now - so it should be buildable for you again.

**Comment by tj800x** [comment]
Thanks.  Glad to see there is a working branch.
