### ISSUE TITLE
Avoid overflows in GCounter

### ISSUE THREAD

**Issue by mfelsche** [jemc/pony-crdt#4]
The `GCounter` CRDT has some edge cases that i detected when working on #3 : 

When the counter overflows its semantics will diverge from that of an unsigned pony int type of the same bit-width exposed to the same operations. Taking the deltas from every operation and converging them all into 1 observer GCounter produces different values than all those operations executed against a U64.

The issue can be triggered by inverting this condition: https://github.com/jemc/pony-crdt/pull/3/files#diff-70ec146b69555622adaee9be2ad3dc59R63

Here is an example set of increment operations against 3 replicas:

```[_Cmd(2510874939036516784,2) _Cmd(12541019400656792711,2) _Cmd(11312702074104371432,1) _Cmd(12031805400055958120,2) _Cmd(3643952151996841346,0) _Cmd(1197609864098051077,1) _Cmd(16271896014832131395,1) _Cmd(12392034064941386220,1) _Cmd(9042838547692309912,2) _Cmd(15763871944381915880,0) _Cmd(6483477658071204641,0) _Cmd(15067809861435987680,2) _Cmd(11001561824449142630,0) _Cmd(12030979150637532910,0) _Cmd(9120605991712704809,0) _Cmd(13386727606448877994,0) _Cmd(1731875364189521547,0) _Cmd(8928243648964009778,0) _Cmd(10855760286947205263,2) _Cmd(16761598005320115346,1) _Cmd(16308076779927601176,2) _Cmd(8117855786352716977,2) _Cmd(14224276517123567922,0) _Cmd(9287291173037715334,0) _Cmd(4003273763412183619,2) _Cmd(7180913325941532185,1)]```

In order to avoid diverging behavior in case of overflow and also to improve usability of this counter (e.g. ensure monotonic growth) i would suggest to use summing operations which detect overflow and in this case set the value to the maximum of the used unsigned integer type. This value will then persist for this counter. No further increased will advance the counter beyond that point, avoiding any issues with overflow. Updating the local replica state and `value()` calls summing all replica states both need to cap the growth of the counter at the maximum value.

**Comment by jemc** [comment]
This was a known limitation of the data type (see Caveats & Pitfalls section in [the relevant Jylis docs](https://jemc.github.io/jylis/docs/types/gcount/)).

However, as we discussed offline, I like your proposed solution of quietly saturating the counter value instead of quietly allowing undefined behaviour. :+1:
