### ISSUE TITLE
fails to compile at the moment

### ISSUE THREAD

**Issue by srenatus** [jemc/pony-crdt#6]
It seems like with #73, this started to fail to build: https://circleci.com/gh/jemc/pony-crdt. I've tried, but failed to find why that might be the case... 🤔

**Comment by mfelsche** [comment]
this is unrelated to the pony version, i actually forgot to commit a file. my bad, fixing it.

**Comment by srenatus** [comment]
thanks!

👉 #7

**Comment by jemc** [comment]
Thanks. Gotta get CircleCI hooked up to PRs.
